version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    image: naffles-fund-management/node-app:production
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 15s
    volumes:
      - ./:/app
      - /app/node_modules
      - ./.env.production:/app/.env.production
    env_file:
      - .env.production
    depends_on:
      - redis
    command: node index.js

  redis:
    image: redis