version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: localhost
    image: naffles-fund-management/node-app:localhost
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 15s
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env.localhost
    depends_on:
      - redis
    command: npm run dev

  redis:
    image: redis